### ISSUE TITLE
Request for pretrained-model

### ISSUE THREAD

**Issue by KeVinGGaoo** [xionghonglin/CRL_MICCAI_2024#1]
Thank you for your excellent work! I've read your paper for several times and i found that the training progress needs paired multi-contrast images with various parameters, but it's hard to get them. So can you share your pre-trained model used in your paper?
Thanks

**Comment by xionghonglin** [comment]
Thank you for your question. However, as mentioned in the paper, we used a small-scale dataset, so the pretrained weights likely won't be helpful for you. However, you may want to check out our new work, which should be more useful - arxiv link https://arxiv.org/abs/2409.16818, github link https://github.com/Wangyulin-user/TUMSyn

**Comment by KeVinGGaoo** [comment]
thanks so much for your advice! I'll try your new work!
